name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Debug:list workspace and show firebase.json
        run: |
          echo "PWD: $(pwd)"
          ls -la
          echo "firebase.json exists?"
          if [ -f firebase.json ]; then echo "yes"; else echo "no"; fi
          echo "public exists?"
          if [ -d public ]; then ls -la public || true; else echo "no public"; fi

      - name: Setup Firebase credentials (write secret to file)
        run: |
          # write secret contents to file (preserve newlines)
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${{ github.workspace }}/firebase-service-account.json"
          ls -la "${{ github.workspace }}/firebase-service-account.json"
          # show file size (bytes) to verify it was written
          wc -c "${{ github.workspace }}/firebase-service-account.json" || true

      - name: Inspect written service account file (safe checks)
        run: |
          F="${{ github.workspace }}/firebase-service-account.json"
          echo "FILE: $F"
          echo "size(bytes): $(wc -c < "$F" || true)"

          # find first non-whitespace byte/char (print readable char or byte value)
          python - <<'PY'
import sys
p=sys.argv[1]
b=open(p,'rb').read()
for x in b:
    if x not in (9,10,13,32):
        if 32<=x<=126:
            print("first_non_ws_char:", chr(x))
        else:
            print("first_non_ws_byte:", x)
        break
else:
    print("first_non_ws: EMPTY")
PY
          # detect if file begins with triple backticks
          if head -n1 "$F" | grep -q '^```'; then echo "NOTE: file starts with triple backticks (remove them)"; fi

          # detect if file contains literal backslash-n sequences (escaped newlines)
          if grep -q '\\\\n' "$F"; then echo "NOTE: file contains literal '\\n' sequences (looks escaped)"; fi

          # detect UTF-8 BOM (EF BB BF)
          if head -c3 "$F" | od -An -t x1 | tr -d ' \n' | grep -qi '^efbbbf'; then echo "NOTE: file starts with UTF-8 BOM (EF BB BF)"; fi


      - name: Validate service account (print client_email only)
        run: |
          # print just the client_email to verify JSON parse without exposing private key
          node -e "console.log(require(process.env.GITHUB_WORKSPACE + '/firebase-service-account.json').client_email)"
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}

      - name: Deploy to Firebase Hosting (production)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json
        run: |
          npx firebase-tools --version
          npx firebase-tools deploy --only hosting --project padakpadak-d5725 --non-interactive
