name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Debug:env, node/npm/npx, list files
        run: |
          echo "== env =="
          env | sort
          echo "== node/npm/npx versions =="
          node -v || true
          npm -v || true
          npx -v || true
          echo "== which npx =="
          which npx || where npx || true
          echo "== workspace list =="
          pwd
          ls -la
          echo "== show firebase.json (if exists) =="
          if [ -f firebase.json ]; then cat firebase.json; else echo "firebase.json not found"; fi
          echo "== list public folder =="
          ls -la public || echo "no public"

      - name: Setup Firebase credentials
        run: |
          # safer write to file preserving newlines
          printf '%s' "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > "${{ github.workspace }}/firebase-service-account.json"

      - name: Deploy to Firebase Hosting (production)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json
        run: |
          # optional: show version
          npx firebase-tools --version
          # deploy to hosting (production/live)
          npx firebase-tools deploy --only hosting --project padakpadak-d5725 --non-interactive
